### ISSUE TITLE
Not able to import an existing account as first step

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-xt-wallet#23] opened 2022-03-09 05:59 UTC
**Describe the bug**
I installed XT on Brave. I tried to import an existing account as first step.
Brave shows an error after i added the passphrase and hit the button.

**Expected behavior**
Should be able to add an existing account as first step on Brave.

**Screenshots**
![brave1](https://user-images.githubusercontent.com/39116221/157381460-d65c803e-d71f-4a70-9a66-c0eabc7724a6.png)

**Browser (please complete the following information):**
 - OS:Windows 10
 - Browser . Brave

**Additional context**

**Comment by paulpoco** [comment] 2022-03-09 06:41
Same on Chrome

**Comment by ohager** [comment] 2022-03-09 09:51
Not reproducable

**Comment by ohager** [comment] 2022-03-09 09:51
Not reproducible

Neither on Chrome, nor on Brave

Tested on:

[Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit)](https://brave.com/latest/)
Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by ohager** [comment] 2022-03-09 09:52
Do you have any connections open

**Comment by ohager** [comment] 2022-03-09 11:16
Ok. I have a theory what happened. I need to assume that you waited for a certain time (like 5 minutes) before you started to import. 
Background: 
The Manifest Version 3 runs so called service workers, which goes "offline" (being inactive) after a certain time period. When this happens, the service worker disconnects from the Messaging API. So the port being used does not exist anymore....and causing a communication faiilure. I was able to reproduce this on the signumart platform. I waited until the service worker became inactive and tried to sign a transaction, which caused an error then. 

Google did an awesome job. Congrats!

Just for the records: Service Worker do not go inactive when using Developer Mode :roll_eyes:

**Comment by ohager** [comment] 2022-03-09 13:36
I close this as duplicate of #24

**Closed as completed by ohager** 2022-03-09 13:36 UTC
Labels: bug
