### ISSUE TITLE
DistributionToHolder is missing in the Activity view

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-xt-wallet#40] opened 2022-07-12 04:54 UTC
**Describe the bug**
DistributionToHolder transaction and amount is not shown in the Activity

**To Reproduce**
Check https://chain.signum.network/tx/9746765727131812603 
Here I have 2 accounts which got a distribution

Missing for account:  https://chain.signum.network/address/9613514220065540170
Correct displayed for account:  https://chain.signum.network/address/13112229684715917355

**Expected behavior**
Distribution for Holder should be shown in Activity with the correct amount

**Screenshots**
Correct:

![grafik](https://user-images.githubusercontent.com/39116221/178411219-6210e904-cf67-49cf-8023-21033fc1354a.png)

Missing:
![grafik](https://user-images.githubusercontent.com/39116221/178411338-7531cd2f-fd4f-4ce7-b0d6-cd8d9184248d.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - XT-Wallet Version [1.2.2]

**Comment by ohager** [comment] 2022-07-12 16:23
Outgoing distribution is not shown

![image](https://user-images.githubusercontent.com/3920663/178543572-a9b34728-5e4f-4393-9b77-958908fa7b5d.png)

but being fetched...

**Comment by ohager** [comment] 2022-09-15 11:15
duplicate of #49

**Closed as completed by ohager** 2022-09-15 11:15 UTC
Labels: bug
